name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
    - "!*-*"
jobs:
  tests:
    uses: ./.github/workflows/phpstan.yml
  tag:
    name: New tag
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
    # Create artifacts
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}.zip
        path: ${{ github.event.repository.name }}.zip
    # Create release
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ github.event.repository.name }}.zip
        name: Release ${{ github.ref_name }}
